name: Biome

on:
  pull_request:
  push:
    branches:
      - staging
      - master
      - main
      - dev

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.5.0

      - name: Run Biome
        run: biome ci .
